In [ ]:
#1. Library Imports
import pandas as pd
import glob
import os

In [ ]:
#2. Load CSV Files
path = "/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/*.csv"
files = sorted(glob.glob(path))
print(files)

['/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202503-divvy-tripdata.csv', '/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202504-divvy-tripdata.csv', '/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202505-divvy-tripdata.csv', '/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202506-divvy-tripdata.csv', '/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202507-divvy-tripdata.csv', '/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202508-divvy-tripdata.csv', '/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202509-divvy-tripdata.csv', '/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202510-divvy-tripdata.csv', '/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202511-divvy-tripdata.csv', '/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202512-divvy-tripdata.csv', '/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202601-divvy-tripdata.csv', '/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202602-divvy-tripdata.csv']

In [ ]:
#3. Combining Datasets
data = []
for i in files:
    print("Loading: ", i)
    temp_df = pd.read_csv(i)
    data.append(temp_df)

df = pd.concat(data, ignore_index=True)
print("Dataset Shape: ", df.shape)

Loading:  /Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202503-divvy-tripdata.csv
Loading:  /Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202504-divvy-tripdata.csv
Loading:  /Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202505-divvy-tripdata.csv
Loading:  /Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202506-divvy-tripdata.csv
Loading:  /Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202507-divvy-tripdata.csv
Loading:  /Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202508-divvy-tripdata.csv
Loading:  /Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202509-divvy-tripdata.csv
Loading:  /Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202510-divvy-tripdata.csv
Loading:  /Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202511-divvy-tripdata.csv
Loading:  /Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202512-divvy-tripdata.csv
Loading:  /Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202601-divvy-tripdata.csv
Loading:  /Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/202602-divvy-tripdata.csv
Dataset Shape:  (5601662, 13)

In [ ]:
#4. Dataset Inspection
df.info()
#df.head()
df["member_casual"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5601662 entries, 0 to 5601661
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 555.6+ MB

member_casual
member    3588150
casual    2013512
Name: count, dtype: int64

In [8]:
#5. Converting Time Columns to Datetime
df["started_at"] = pd.to_datetime(df["started_at"])
df["ended_at"] = pd.to_datetime(df["ended_at"])

In [10]:
#6. Ride Duration Feature Creation
df["ride_length"] = df["ended_at"] - df["started_at"]
df["ride_length_min"] = df["ride_length"].dt.total_seconds() / 60 # Convert to minutes
df["ride_length"].describe()

count                      5601662
mean     0 days 00:16:05.776201919
std      0 days 00:55:48.744660378
min       -1 days +23:05:12.312000
25%         0 days 00:05:23.857000
50%         0 days 00:09:26.049000
75%         0 days 00:16:35.159000
max         1 days 02:14:54.011000
Name: ride_length, dtype: object

In [12]:
#7. Removing Invalid Rides and Duplicates
df = df[df["ride_length_min"] > 0] # Remove rides with negative or zero duration
df = df.drop_duplicates() # Remove duplicate rows
print("Dataset Shape after cleaning: ", df.shape)
df.head()

Dataset Shape after cleaning:  (5601633, 15)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,ride_length_min
0,16CBE9844D401954,electric_bike,2025-03-18 08:39:20.065,2025-03-18 08:51:37.633,NaN,NaN,Canal St & Jackson Blvd,13138,41.91,-87.67,41.878125,-87.639968,member,0 days 00:12:17.568000,12.292800
1,1CB408029E2B5F74,electric_bike,2025-03-24 16:04:22.239,2025-03-24 16:27:41.347,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.86,-87.68,41.914027,-87.705126,member,0 days 00:23:19.108000,23.318467
2,7B6A76CD0F204D08,electric_bike,2025-03-10 16:06:19.708,2025-03-10 16:29:17.457,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.86,-87.68,41.914027,-87.705126,member,0 days 00:22:57.749000,22.962483
3,4F7084E3D75CDE31,electric_bike,2025-03-21 14:28:14.579,2025-03-21 14:35:06.160,NaN,NaN,Canal St & Jackson Blvd,13138,41.87,-87.63,41.878125,-87.639968,member,0 days 00:06:51.581000,6.859683
4,E419A570A5A0475B,electric_bike,2025-03-14 17:54:14.484,2025-03-14 18:17:53.254,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.89,-87.67,41.914027,-87.705126,casual,0 days 00:23:38.770000,23.646167

In [13]:
#8. Feature Engineering - Extracting Date Components
df["day_of_week"] = df["started_at"].dt.day_name()
df["month"] = df["started_at"].dt.month_name()
df["hour"] = df["started_at"].dt.hour
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,ride_length_min,day_of_week,month,hour
0,16CBE9844D401954,electric_bike,2025-03-18 08:39:20.065,2025-03-18 08:51:37.633,NaN,NaN,Canal St & Jackson Blvd,13138,41.91,-87.67,41.878125,-87.639968,member,0 days 00:12:17.568000,12.292800,Tuesday,March,8
1,1CB408029E2B5F74,electric_bike,2025-03-24 16:04:22.239,2025-03-24 16:27:41.347,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.86,-87.68,41.914027,-87.705126,member,0 days 00:23:19.108000,23.318467,Monday,March,16
2,7B6A76CD0F204D08,electric_bike,2025-03-10 16:06:19.708,2025-03-10 16:29:17.457,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.86,-87.68,41.914027,-87.705126,member,0 days 00:22:57.749000,22.962483,Monday,March,16
3,4F7084E3D75CDE31,electric_bike,2025-03-21 14:28:14.579,2025-03-21 14:35:06.160,NaN,NaN,Canal St & Jackson Blvd,13138,41.87,-87.63,41.878125,-87.639968,member,0 days 00:06:51.581000,6.859683,Friday,March,14
4,E419A570A5A0475B,electric_bike,2025-03-14 17:54:14.484,2025-03-14 18:17:53.254,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.89,-87.67,41.914027,-87.705126,casual,0 days 00:23:38.770000,23.646167,Friday,March,17

In [14]:
#9. Data Validation
df["ride_length_min"].describe()
df.isnull().sum()
df["member_casual"].value_counts()

member_casual
member    3588130
casual    2013503
Name: count, dtype: int64

In [16]:
#10. Exporting Cleaned Dataset
output_path = "/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/cleaned_cyclistic_data.csv"
df.to_csv(output_path, index=False)

In [21]:
#11. Cleaned Dataset Inspection
df = pd.read_csv("/Users/spandanmaharana/Desktop/BI Case Studies/Case Study 1/Cyclistic Case Study/data/cleaned_cyclistic_data.csv")
print(df.dtypes)
df.head(10)

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
ride_length            object
ride_length_min       float64
day_of_week            object
month                  object
hour                    int64
dtype: object

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,ride_length_min,day_of_week,month,hour
0,16CBE9844D401954,electric_bike,2025-03-18 08:39:20.065,2025-03-18 08:51:37.633,NaN,NaN,Canal St & Jackson Blvd,13138,41.910000,-87.670000,41.878125,-87.639968,member,0 days 00:12:17.568000,12.292800,Tuesday,March,8
1,1CB408029E2B5F74,electric_bike,2025-03-24 16:04:22.239,2025-03-24 16:27:41.347,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.860000,-87.680000,41.914027,-87.705126,member,0 days 00:23:19.108000,23.318467,Monday,March,16
2,7B6A76CD0F204D08,electric_bike,2025-03-10 16:06:19.708,2025-03-10 16:29:17.457,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.860000,-87.680000,41.914027,-87.705126,member,0 days 00:22:57.749000,22.962483,Monday,March,16
3,4F7084E3D75CDE31,electric_bike,2025-03-21 14:28:14.579,2025-03-21 14:35:06.160,NaN,NaN,Canal St & Jackson Blvd,13138,41.870000,-87.630000,41.878125,-87.639968,member,0 days 00:06:51.581000,6.859683,Friday,March,14
4,E419A570A5A0475B,electric_bike,2025-03-14 17:54:14.484,2025-03-14 18:17:53.254,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.890000,-87.670000,41.914027,-87.705126,casual,0 days 00:23:38.770000,23.646167,Friday,March,17
5,79FBC35C1715F60C,electric_bike,2025-03-24 16:14:36.782,2025-03-24 16:18:28.788,NaN,NaN,Canal St & Jackson Blvd,13138,41.890000,-87.640000,41.878125,-87.639968,member,0 days 00:03:52.006000,3.866767,Monday,March,16
6,715E2B8DFC893AD8,electric_bike,2025-03-18 19:37:16.225,2025-03-18 19:45:43.146,NaN,NaN,Clybourn Ave & Division St,TA1307000115,41.910000,-87.670000,41.904613,-87.640552,member,0 days 00:08:26.921000,8.448683,Tuesday,March,19
7,13C9D648D25C5A8B,classic_bike,2025-03-08 21:42:08.903,2025-03-08 21:49:17.893,California Ave & Milwaukee Ave,13084,Albany Ave & Bloomingdale Ave,15655,41.922695,-87.697153,41.914027,-87.705126,member,0 days 00:07:08.990000,7.149833,Saturday,March,21
8,726F12BE953D7C96,electric_bike,2025-03-06 14:43:34.632,2025-03-06 14:50:40.668,NaN,NaN,Canal St & Jackson Blvd,13138,41.890000,-87.630000,41.878125,-87.639968,member,0 days 00:07:06.036000,7.100600,Thursday,March,14
9,13751EA8835DB24A,electric_bike,2025-03-28 16:12:45.261,2025-03-28 17:10:52.599,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.750000,-87.720000,41.914027,-87.705126,member,0 days 00:58:07.338000,58.122300,Friday,March,16